[package]
name = "rust_crypto_challenges"
version = "1.0.0"
authors = ["fotcorn <fotcorn@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/fotcorn/rust_crypto_challenges"


[dependencies]
rustc-serialize = "*"
rust-crypto = "*"
